window.LAYOUT_ELEMENTS = [
  { key: "scene", name: "Scene", asset: "assets/reloading_sheet.webp", frame: "last" },
  { key: "p1-info", name: "P1 name & info", kind: "text", text: "P1\nINFO", width: 220, height: 72 },
  { key: "p2-info", name: "P2 name & info", kind: "text", text: "P2\nINFO", width: 220, height: 72 },
  { key: "p1-win-label", name: "P1 win label", asset: "assets/wins_label_sheet.webp" },
  { key: "p2-win-label", name: "P2 win label", asset: "assets/wins_label_sheet.webp" },
  { key: "p1-win-counter", name: "P1 win counter", asset: "assets/w1_sheet.webp" },
  { key: "p2-win-counter", name: "P2 win counter", asset: "assets/w1_sheet.webp" },
  { key: "turn-counter", name: "Turn counter", asset: "assets/turn1_sheet.webp" },
  { key: "p1-bullets-label", name: "P1 bullets label", asset: "assets/bullets_label_sheet.webp" },
  { key: "p2-bullets-label", name: "P2 bullets label", asset: "assets/bullets_label_sheet.webp" },
  { key: "p1-bullet-slot-1", name: "P1 bullet slot 1", asset: "assets/bullet_icon_sheet.webp" },
  { key: "p1-bullet-slot-2", name: "P1 bullet slot 2", asset: "assets/bullet_icon_sheet.webp" },
  { key: "p1-bullet-slot-3", name: "P1 bullet slot 3", asset: "assets/bullet_icon_sheet.webp" },
  { key: "p1-bullet-slot-4", name: "P1 bullet slot 4", asset: "assets/bullet_icon_sheet.webp" },
  { key: "p2-bullet-slot-1", name: "P2 bullet slot 1", asset: "assets/bullet_icon_sheet.webp" },
  { key: "p2-bullet-slot-2", name: "P2 bullet slot 2", asset: "assets/bullet_icon_sheet.webp" },
  { key: "p2-bullet-slot-3", name: "P2 bullet slot 3", asset: "assets/bullet_icon_sheet.webp" },
  { key: "p2-bullet-slot-4", name: "P2 bullet slot 4", asset: "assets/bullet_icon_sheet.webp" },
  { key: "p1-waiting-animation", name: "P1 waiting animation", asset: "assets/ready_waiting/waiting3_sheet.webp", frame: "last" },
  { key: "p2-waiting-animation", name: "P2 waiting animation", asset: "assets/ready_waiting/waiting3_sheet.webp", frame: "last" },
  { key: "p1-ready-animation", name: "P1 ready animation", asset: "assets/ready_waiting/rdy_sheet.webp", frame: "last" },
  { key: "p2-ready-animation", name: "P2 ready animation", asset: "assets/ready_waiting/rdy_sheet.webp", frame: "last" },
  { key: "p1-you-picked", name: "P1 you picked", asset: "assets/you_picked_sheet.webp" },
  { key: "p2-they-picked", name: "P2 they picked", asset: "assets/they_picked_sheet.webp" },
  { key: "p1-previous-move-icon", name: "P1 previous move icon", asset: "assets/shoot_icon_sheet.webp" },
  { key: "p2-previous-move-icon", name: "P2 previous move icon", asset: "assets/shoot_icon_sheet.webp" },
  { key: "shoot-button", name: "Shoot button", asset: "assets/shoot_button_sheet.webp" },
  { key: "shoot-decorative-icon", name: "Shoot decorative icon", asset: "assets/shoot_icon_sheet.webp" },
  { key: "stab-button", name: "Stab button", asset: "assets/stab_button_sheet.webp" },
  { key: "stab-decorative-icon", name: "Stab decorative icon", asset: "assets/stab_icon_sheet.webp" },
  { key: "duck-button", name: "Duck button", asset: "assets/duck_button_sheet.webp" },
  { key: "reload-button", name: "Reload button", asset: "assets/reload_button_sheet.webp" },
];
